# Generated by Django 5.1 on 2026-08-25 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external_residences', '0001_initial'),
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('is_group', models.BooleanField(default=False)),
                ('number_of_people', models.PositiveSmallIntegerField(default=1)),
                ('desired_start_date', models.DateField()),
                ('desired_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('alternative_proposed', 'Alternative proposée'), ('alternative_rejected', "Alternative refusée par l'étudiant"), ('confirmed', 'Confirmée définitivement'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=25)),
                ('rejection_reason', models.TextField(blank=True)),
                ('alternative_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_external_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='external_residences.externalresidence')),
                ('alternative_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostels.hostel')),
                ('alternative_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostels.room')),
                ('handled_by', models.ForeignKey(blank=True, help_text='Administrateur ayant traité la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hostels.hostel')),
                ('requested_comfort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostels.comfortoption')),
                ('requested_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostels.roomtype')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hostels.room', verbose_name='Chambre affectée')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_verified', models.BooleanField(default=False)),
                ('damages_notes', models.TextField(blank=True)),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed', models.BooleanField(default=False)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_out', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Check-out',
                'verbose_name_plural': 'Check-outs',
                'db_table': 'check_outs',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_validated', models.BooleanField(default=False)),
                ('key_handed_over', models.BooleanField(default=False)),
                ('room_initial_state', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'db_table': 'check_ins',
            },
        ),
        migrations.CreateModel(
            name='ReservationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('student_number', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(blank=True, max_length=150)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Membre de réservation',
                'verbose_name_plural': 'Membres de réservation',
                'db_table': 'reservation_members',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('student_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro étudiant / matricule')),
                ('program', models.CharField(blank=True, max_length=150, verbose_name='Programme / formation')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='Année académique')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('documents', models.JSONField(blank=True, default=list, help_text='Documents justificatifs (chemins/URLs).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'students',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.student', verbose_name='Étudiant demandeur / responsable du groupe'),
        ),
    ]
