# Generated by Django 4.2.11 on 2026-08-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée souhaitée (en mois)'),
        ),
    ]
