# Generated by Django 4.2.11 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='beds_reserved',
            field=models.PositiveSmallIntegerField(default=1, help_text="Unité de facturation : 1 lit par locataire, ou tous les lits de la chambre s'il la loue en entier.", verbose_name='Lits réservés'),
        ),
    ]
