# Generated by Django 4.2.11 on 2026-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_beds_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('alternative_proposed', 'Alternative proposée'), ('alternative_rejected', "Alternative refusée par l'étudiant"), ('confirmed', 'Confirmée définitivement'), ('cancelled', 'Annulée'), ('expired', 'Expirée'), ('completed', 'Terminée (check-out effectué)')], default='pending', max_length=25),
        ),
    ]
