# Generated by Django 4.2.11 on 2026-09-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_reservation',
            field=models.OneToOneField(blank=True, help_text="Renseigné automatiquement lors d'un transfert de chambre — pointe vers le séjour dont celle-ci prend la suite.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reservation', to='reservations.reservation', verbose_name='Réservation précédente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('alternative_proposed', 'Alternative proposée'), ('alternative_rejected', "Alternative refusée par l'étudiant"), ('confirmed', 'Confirmée définitivement'), ('cancelled', 'Annulée'), ('expired', 'Expirée'), ('completed', 'Terminée (check-out effectué)'), ('transferred', 'Transférée vers une autre chambre')], default='pending', max_length=25),
        ),
    ]
