# Generated by Django 5.1 on 2026-08-25 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('account_created', 'Création de compte'), ('reservation_request_received', 'Demande de réservation reçue'), ('reservation_pending', 'Réservation en attente'), ('reservation_accepted', 'Réservation acceptée'), ('reservation_rejected', 'Réservation rejetée'), ('alternative_proposed', "Proposition d'une chambre alternative"), ('invoice_generated', 'Génération de facture pro-forma'), ('payment_confirmed', 'Confirmation de paiement'), ('payment_reminder', 'Rappel de paiement'), ('balance_remaining', 'Solde restant'), ('reservation_confirmed', 'Confirmation définitive de réservation'), ('reservation_cancelled', 'Annulation'), ('reservation_expired', "Expiration d'une réservation")], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Notification push')], default='email', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
