# Generated by Django 5.1 on 2026-08-25 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComfortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Niveau de confort')),
            ],
            options={
                'verbose_name': 'Option de confort',
                'verbose_name_plural': 'Options de confort',
                'db_table': 'comfort_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hostels/covers/')),
                ('has_external_kitchen', models.BooleanField(default=False, help_text="Particularité de l'Hostel Dzorwulu.", verbose_name='Cuisine externe')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type de chambre')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité (nombre de personnes)')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambre',
                'db_table': 'room_types',
                'ordering': ['capacity'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone/bloc')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='Étage')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='hostels.hostel')),
            ],
            options={
                'verbose_name': 'Zone / Bloc',
                'verbose_name_plural': 'Zones / Blocs',
                'db_table': 'hostel_zones',
                'ordering': ['hostel', 'name'],
                'unique_together': {('hostel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tarif mensuel')),
                ('period_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarif par période')),
                ('electricity_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Frais d'électricité")),
                ('admin_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Frais administratifs')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Caution')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comfort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hostels.comfortoption')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hostels.hostel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hostels.roomtype')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'db_table': 'prices',
                'ordering': ['hostel', 'room_type'],
                'unique_together': {('hostel', 'room_type', 'comfort')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Numéro de chambre')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='Étage')),
                ('electricity_policy', models.CharField(choices=[('included', 'Incluse dans le tarif'), ('excluded', 'Exclue du tarif'), ('additional', 'Tarification complémentaire')], default='included', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservée'), ('occupied', 'Occupée'), ('pending', 'En attente'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service'), ('blocked', 'Bloquée temporairement')], default='available', max_length=20)),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste des URLs/chemins de photos.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='hostels.amenity')),
                ('comfort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostels.comfortoption')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostels.roomtype')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hostels.zone')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'db_table': 'rooms',
                'ordering': ['hostel', 'number'],
                'unique_together': {('hostel', 'number')},
            },
        ),
    ]
