# Generated by Django 4.2.11 on 2026-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='free_cancellation',
            field=models.BooleanField(default=False, help_text="À activer une fois la politique d'annulation confirmée (section 30 du cahier des charges).", verbose_name='Annulation gratuite'),
        ),
    ]
