# Generated by Django 4.2.11 on 2026-09-02 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_hostel_latitude_hostel_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Unité de facturation : chaque lit peut être loué à un locataire distinct.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de lits'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service'), ('blocked', 'Bloquée temporairement')], default='available', max_length=20),
        ),
    ]
