# Generated by Django 5.1 on 2026-08-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Personne responsable')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number_of_rooms', models.PositiveIntegerField(default=0, verbose_name='Nombre de chambres')),
                ('characteristics', models.TextField(blank=True, verbose_name='Caractéristiques')),
                ('tariffs_notes', models.TextField(blank=True, verbose_name='Tarifs (notes libres)')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Résidence externe',
                'verbose_name_plural': 'Résidences externes',
                'db_table': 'external_residences',
                'ordering': ['name'],
            },
        ),
    ]
