// Indicatifs téléphoniques — pays d'Afrique de l'Ouest en premier (public cible du site),
// puis le reste du monde par ordre alphabétique.
export const COUNTRY_CODES = [
  { name: 'Ghana', dial: '+233' },
  { name: 'Burkina Faso', dial: '+226' },
  { name: "Côte d'Ivoire", dial: '+225' },
  { name: 'Togo', dial: '+228' },
  { name: 'Bénin', dial: '+229' },
  { name: 'Mali', dial: '+223' },
  { name: 'Niger', dial: '+227' },
  { name: 'Sénégal', dial: '+221' },
  { name: 'Nigeria', dial: '+234' },
  { name: 'Guinée', dial: '+224' },
  { name: 'Cameroun', dial: '+237' },
  { name: '—', dial: '' },
  { name: 'Afrique du Sud', dial: '+27' },
  { name: 'Algérie', dial: '+213' },
  { name: 'Allemagne', dial: '+49' },
  { name: 'Belgique', dial: '+32' },
  { name: 'Canada', dial: '+1' },
  { name: 'Chine', dial: '+86' },
  { name: 'Espagne', dial: '+34' },
  { name: 'États-Unis', dial: '+1' },
  { name: 'France', dial: '+33' },
  { name: 'Inde', dial: '+91' },
  { name: 'Italie', dial: '+39' },
  { name: 'Liban', dial: '+961' },
  { name: 'Maroc', dial: '+212' },
  { name: 'Royaume-Uni', dial: '+44' },
  { name: 'Suisse', dial: '+41' },
  { name: 'Tunisie', dial: '+216' },
]

export const DEFAULT_COUNTRY_DIAL = '+233'
